import {
  Accessibility,
  AlarmClock,
  AlertTriangle,
  Armchair,
  Award,
  Baby,
  Backpack,
  Ban,
  Bell,
  BellOff,
  BookOpen,
  Briefcase,
  Bus,
  Calendar,
  Camera,
  CameraOff,
  Car,
  CheckCircle,
  CigaretteOff,
  Clock,
  Coffee,
  Compass,
  CreditCard,
  CupSoda,
  Dog,
  DoorOpen,
  Eye,
  EyeOff,
  FileText,
  Flame,
  Footprints,
  Gift,
  Hand,
  Heart,
  Info,
  Key,
  Landmark,
  Lock,
  Luggage,
  MapPin,
  Mic,
  Music,
  Music2,
  Phone,
  ParkingCircle,
  Shield,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  Snowflake,
  Sparkles,
  Star,
  Ticket,
  Train,
  Umbrella,
  Users,
  Video,
  Volume2,
  VolumeX,
  Wifi,
  Wine,
  XCircle,
  Zap,
  type LucideIcon,
} from 'lucide-react';

/* ============================================================ */
/* Реестр Lucide-иконок, доступных для выбора в админке.        */
/* Один источник правды и для пикера (админка), и для рендера   */
/* (страница «Зрителям»). Имя иконки хранится строкой в данных. */
/* ============================================================ */

export const ICON_REGISTRY: Record<string, LucideIcon> = {
  Accessibility,
  AlarmClock,
  AlertTriangle,
  Armchair,
  Award,
  Baby,
  Backpack,
  Ban,
  Bell,
  BellOff,
  BookOpen,
  Briefcase,
  Bus,
  Calendar,
  Camera,
  CameraOff,
  Car,
  CheckCircle,
  CigaretteOff,
  Clock,
  Coffee,
  Compass,
  CreditCard,
  CupSoda,
  Dog,
  DoorOpen,
  Eye,
  EyeOff,
  FileText,
  Flame,
  Footprints,
  Gift,
  Hand,
  Heart,
  Info,
  Key,
  Landmark,
  Lock,
  Luggage,
  MapPin,
  Mic,
  Music,
  Music2,
  Phone,
  ParkingCircle,
  Shield,
  ShieldCheck,
  Shirt,
  ShoppingBag,
  Snowflake,
  Sparkles,
  Star,
  Ticket,
  Train,
  Umbrella,
  Users,
  Video,
  Volume2,
  VolumeX,
  Wifi,
  Wine,
  XCircle,
  Zap,
};

/** Имена всех доступных иконок (для пикера). */
export const ICON_NAMES: string[] = Object.keys(ICON_REGISTRY);

/** Иконка по умолчанию, если имя пустое/неизвестно. */
export const DEFAULT_ICON_NAME = 'Info';

/** Достаёт компонент иконки по имени; при неизвестном имени — запасная. */
export function getLucideIcon(name: string | undefined | null): LucideIcon {
  if (name && ICON_REGISTRY[name]) return ICON_REGISTRY[name];
  return ICON_REGISTRY[DEFAULT_ICON_NAME];
}
